import Head from "next/head"
import { getFeaturesData } from "@/datalayer"
import { FeatureCard } from "@/components/data/cards/FeaturesSection"
import { TFeature } from "@/components/data/cards/FeaturesSection"

type TFeaturePageProps = {
  featuresData: TFeature[]
}

export default function Features({ featuresData }: TFeaturePageProps) {
  console.log(featuresData)
  return (
    <>
      <Head>
        <title>iGyanam.com</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon/favicon.ico" />
      </Head>

      <div className="mt-20">
        <h1 className="text-center">Gyanam Test Generator Features</h1>
        <h3 className="mt-4 text-center text-gray-600">
          Features which will improve your results, productivity & quality of
          education. It will also help you to save a lot of extra time.
        </h3>
        <div className="grid grid-cols-2 gap-4 my-10">
          {featuresData.map(feature => (
            <FeatureCard
              key={feature.featureTitle}
              featureTitle={feature.featureTitle}
              featureDescription={feature.featureDescription}
              featureVideo={feature.featureVideo}
              imgUrl={feature.featureImage.url}
            />
          ))}
        </div>
      </div>
    </>
  )
}

export const getServerSideProps = async () => {
  const featuresData = await getFeaturesData()
  console.log(featuresData)
  return {
    props: {
      featuresData
    }
  }
}
