import Head from "next/head"
import HomePage from "@/components/ui/HomePage"
import { getHomePageData } from "@/datalayer"

export default function Index({ homePageData }) {
  return (
    <>
      <Head>
        <title>iGyanam.com</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon/favicon.ico" />
      </Head>
      <HomePage homePageData={homePageData} />
    </>
  )
}

export const getStaticProps = async () => {
  const homePageData = await getHomePageData()
  return {
    props: {
      homePageData
    }
  }
}
